#!/bin/bash

load inquirer

check() {
  if [ ! -d $SERVICE_V2FLY_SSL ]; then
    log::error "Please prepare ssl($(color::green "fullchain.pem + privkey.pem")) in $(color::green $SERVICE_V2FLY_SSL)"
    exit 1
  fi

  config::load_file $SERVICE_CONFIG
  if [ -z "$SERVICE_V2FLY_ID" ]; then
    inquirer::text "请输入 USER ID:" value $(os::uuid)
    config::set SERVICE_V2FLY_ID $value $SERVICE_CONFIG
  fi

  export SERVICE_V2FLY_ID=$SERVICE_V2FLY_ID
}

check $@
