#!/bin/bash

load inquirer

check() {
  if [ -n "$SERVICE_V2FLY_CUSTOM_SSL" ]; then
    export SERVICE_V2FLY_SSL=$SERVICE_V2FLY_CUSTOM_SSL
  fi

  if [ ! -f $SERVICE_CONFIG ]; then
    touch $SERVICE_CONFIG
  fi

  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_V2FLY_ID" ]; then
    inquirer::text "请输入 USER ID:" value $(os::uuid)
    config::set SERVICE_V2FLY_ID $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_V2FLY_MODE" ]; then
    local choices=(
      "https"
      "http"
    )
    inquirer::select "请输入 MODE:" choices value
    config::set SERVICE_V2FLY_MODE $value $SERVICE_CONFIG
  fi

  if [ "$SERVICE_V2FLY_MODE" = "https" ]; then
    if [ ! -f "$SERVICE_V2FLY_SSL/fullchain.pem" ]; then
      log::error "Please prepare ssl($(color::green "fullchain.pem + privkey.pem")) in $(color::green $SERVICE_V2FLY_SSL)"
      exit 1
    fi
  fi

  config::load_file $SERVICE_CONFIG

  log::debug "[service][$SERVICE_V2FLY_NAME] SERVICE_V2FLY_ID: $SERVICE_V2FLY_ID"
  log::debug "[service][$SERVICE_V2FLY_NAME] SERVICE_V2FLY_MODE: $SERVICE_V2FLY_MODE"
  log::debug "[service][$SERVICE_V2FLY_NAME] SERVICE_V2FLY_SSL: $SERVICE_V2FLY_SSL"

  export SERVICE_V2FLY_ID=$SERVICE_V2FLY_ID
  export SERVICE_V2FLY_MODE=$SERVICE_V2FLY_MODE
}

check $@
